apiVersion: v1
kind: Job
metadata:
  name: my-app-pod
spec:
  backoffLimit: 1
  initContainers:
  - name: liquibase
    image: liquibase/liquibase:latest
    command: ["liquibase", "update", "--changeLogFile=/liquibase/changelog/changelog.xml"]
    env:
    - name: LIQUIBASE_URL
      value: "jdbc:mysql://mysql:5432/mydb"
    - name: LIQUIBASE_USERNAME
      value: "myuser"
    - name: LIQUIBASE_PASSWORD
      value: "mypassword"
    volumeMounts:
    - name: liquibase-changelog-volume
      mountPath: /liquibase/changelog
  volumes:
  - name: liquibase-changelog-volume
    configMap:
      name: liquibase-changelog
